import type { Listing } from "@easyfinderai/shared";

type ListingSeed = Omit<Listing, "imageUrl" | "images"> & {
  imageQueries: string[];
  imageSeed: number;
};

const buildImages = (queries: string[], seed: number) =>
  queries.map(
    (query, index) =>
      `https://source.unsplash.com/featured/1200x800/?${encodeURIComponent(query)}&sig=${
        seed + index
      }`
  );

const makeListing = (listing: ListingSeed): Listing => {
  const { imageQueries, imageSeed, ...rest } = listing;
  const images = buildImages(imageQueries, imageSeed);
  return {
    ...rest,
    imageUrl: images[0],
    images,
  };
};

export const demoListings: Listing[] = [
  makeListing({
    id: "demo-1",
    title: "2020 CAT 320 Excavator",
    description: "Well-maintained excavator with low hours and clean service logs.",
    state: "CA",
    price: 178000,
    hours: 1800,
    operable: true,
    category: "Excavator",
    imageQueries: [
      "cat 320 excavator",
      "crawler excavator construction",
      "hydraulic excavator digging",
      "excavator heavy equipment",
    ],
    imageSeed: 101,
    source: "auctionplanet",
    createdAt: "2025-12-10T15:12:00.000Z",
  }),
  makeListing({
    id: "demo-2",
    title: "2018 Komatsu PC210 Excavator",
    description: "Job-ready excavator with fresh undercarriage inspection.",
    state: "TX",
    price: 154000,
    hours: 3200,
    operable: true,
    category: "Excavator",
    imageQueries: [
      "komatsu pc210 excavator",
      "excavator bucket close up",
      "earthmoving excavator worksite",
      "construction excavator cab",
    ],
    imageSeed: 111,
    source: "ironplanet",
    createdAt: "2025-12-08T10:35:00.000Z",
  }),
  makeListing({
    id: "demo-3",
    title: "2016 Deere 210G Excavator",
    description: "Balanced excavator with mid-range hours and strong hydraulics.",
    state: "NV",
    price: 122000,
    hours: 4100,
    operable: true,
    category: "Excavator",
    imageQueries: [
      "deere excavator",
      "excavator tracks",
      "excavator on job site",
      "excavator boom",
    ],
    imageSeed: 121,
    source: "machinerytrader",
    createdAt: "2025-12-05T09:20:00.000Z",
  }),
  makeListing({
    id: "demo-4",
    title: "2021 Volvo EC250 Excavator",
    description: "Late-model excavator, warranty transfer available.",
    state: "AZ",
    price: 206000,
    hours: 950,
    operable: true,
    category: "Excavator",
    imageQueries: [
      "volvo excavator",
      "excavator loading dirt",
      "excavator on construction site",
      "modern excavator",
    ],
    imageSeed: 131,
    source: "auctiontime",
    createdAt: "2025-12-12T11:00:00.000Z",
  }),
  makeListing({
    id: "demo-5",
    title: "2017 CAT D6T Dozer",
    description: "Strong push power with updated blade hydraulics.",
    state: "IA",
    price: 198000,
    hours: 3600,
    operable: true,
    category: "Dozer",
    imageQueries: [
      "cat d6 bulldozer",
      "bulldozer pushing dirt",
      "dozer blade earthmoving",
      "track dozer construction",
    ],
    imageSeed: 201,
    source: "ritchiebros",
    createdAt: "2025-12-03T14:40:00.000Z",
  }),
  makeListing({
    id: "demo-6",
    title: "2015 Komatsu D65 Dozer",
    description: "Reliable dozer with premium undercarriage.",
    state: "CO",
    price: 148000,
    hours: 5200,
    operable: true,
    category: "Dozer",
    imageQueries: [
      "komatsu bulldozer",
      "dozer on quarry",
      "bulldozer tracks",
      "bulldozer worksite",
    ],
    imageSeed: 211,
    source: "ironplanet",
    createdAt: "2025-11-28T12:15:00.000Z",
  }),
  makeListing({
    id: "demo-7",
    title: "2019 Deere 650K Dozer",
    description: "Low-hour dozer with GPS-ready blade controls.",
    state: "TX",
    price: 214000,
    hours: 1400,
    operable: true,
    category: "Dozer",
    imageQueries: [
      "deere dozer",
      "bulldozer grading",
      "dozer blade detail",
      "bulldozer earthmoving",
    ],
    imageSeed: 221,
    source: "auctionplanet",
    createdAt: "2025-12-09T09:05:00.000Z",
  }),
  makeListing({
    id: "demo-8",
    title: "2014 CAT D5K Dozer",
    description: "Compact dozer, strong for tight sites.",
    state: "WA",
    price: 98000,
    hours: 6400,
    operable: true,
    category: "Dozer",
    imageQueries: [
      "cat d5 bulldozer",
      "small dozer",
      "bulldozer compact",
      "dozer on dirt site",
    ],
    imageSeed: 231,
    source: "govplanet",
    createdAt: "2025-11-20T16:55:00.000Z",
  }),
  makeListing({
    id: "demo-9",
    title: "2020 CAT 262D Skid Steer",
    description: "Compact skid steer with new tires and cab.",
    state: "AZ",
    price: 72000,
    hours: 1100,
    operable: true,
    category: "Skid Steer",
    imageQueries: [
      "cat skid steer",
      "skid steer loader",
      "skid steer construction",
      "compact skid steer",
    ],
    imageSeed: 301,
    source: "auctiontime",
    createdAt: "2025-12-11T08:30:00.000Z",
  }),
  makeListing({
    id: "demo-10",
    title: "2018 Bobcat S650 Skid Steer",
    description: "High-flow skid steer with attachment package.",
    state: "CA",
    price: 68000,
    hours: 1900,
    operable: true,
    category: "Skid Steer",
    imageQueries: [
      "bobcat skid steer",
      "skid steer bucket",
      "skid steer worksite",
      "skid steer attachment",
    ],
    imageSeed: 311,
    source: "heavyequipment",
    createdAt: "2025-12-01T10:10:00.000Z",
  }),
  makeListing({
    id: "demo-11",
    title: "2016 Deere 318G Skid Steer",
    description: "Well-kept skid steer with enclosed cab.",
    state: "OR",
    price: 52000,
    hours: 2900,
    operable: true,
    category: "Skid Steer",
    imageQueries: [
      "deere skid steer",
      "compact track loader",
      "skid steer cab",
      "skid steer lifting",
    ],
    imageSeed: 321,
    source: "machinerytrader",
    createdAt: "2025-11-25T15:20:00.000Z",
  }),
  makeListing({
    id: "demo-12",
    title: "2021 Takeuchi TL12 Skid Steer",
    description: "Track skid steer, low hours, clean emissions.",
    state: "TX",
    price: 89000,
    hours: 800,
    operable: true,
    category: "Skid Steer",
    imageQueries: [
      "takeuchi skid steer",
      "track skid steer",
      "skid steer on gravel",
      "skid steer loader work",
    ],
    imageSeed: 331,
    source: "auctionplanet",
    createdAt: "2025-12-13T13:25:00.000Z",
  }),
  makeListing({
    id: "demo-13",
    title: "2019 CAT 930M Wheel Loader",
    description: "Production-ready loader with scale system.",
    state: "NV",
    price: 162000,
    hours: 2800,
    operable: true,
    category: "Wheel Loader",
    imageQueries: [
      "cat wheel loader",
      "front end loader",
      "wheel loader bucket",
      "loader at quarry",
    ],
    imageSeed: 401,
    source: "ironplanet",
    createdAt: "2025-12-07T12:45:00.000Z",
  }),
  makeListing({
    id: "demo-14",
    title: "2017 Volvo L90 Wheel Loader",
    description: "Efficient loader with updated bucket pins.",
    state: "CA",
    price: 148000,
    hours: 4200,
    operable: true,
    category: "Wheel Loader",
    imageQueries: [
      "volvo wheel loader",
      "wheel loader working",
      "loader construction site",
      "front loader equipment",
    ],
    imageSeed: 411,
    source: "ritchiebros",
    createdAt: "2025-12-02T09:00:00.000Z",
  }),
  makeListing({
    id: "demo-15",
    title: "2015 Deere 544K Wheel Loader",
    description: "Durable loader with strong tire condition.",
    state: "UT",
    price: 118000,
    hours: 6100,
    operable: true,
    category: "Wheel Loader",
    imageQueries: [
      "deere wheel loader",
      "wheel loader gravel",
      "loader tire close up",
      "loader earthmoving",
    ],
    imageSeed: 421,
    source: "auctiontime",
    createdAt: "2025-11-22T11:35:00.000Z",
  }),
  makeListing({
    id: "demo-16",
    title: "2022 Komatsu WA270 Wheel Loader",
    description: "Late-model loader with low hours and warranty.",
    state: "AZ",
    price: 224000,
    hours: 600,
    operable: true,
    category: "Wheel Loader",
    imageQueries: [
      "komatsu wheel loader",
      "modern wheel loader",
      "loader on jobsite",
      "wheel loader bucket lift",
    ],
    imageSeed: 431,
    source: "machinerytrader",
    createdAt: "2025-12-14T10:50:00.000Z",
  }),
  makeListing({
    id: "demo-17",
    title: "2018 CAT 420F Backhoe",
    description: "Backhoe with extendahoe and clean hydraulics.",
    state: "TX",
    price: 98000,
    hours: 2300,
    operable: true,
    category: "Backhoe",
    imageQueries: [
      "cat backhoe loader",
      "backhoe digging",
      "backhoe on site",
      "backhoe loader bucket",
    ],
    imageSeed: 501,
    source: "govplanet",
    createdAt: "2025-12-04T08:20:00.000Z",
  }),
  makeListing({
    id: "demo-18",
    title: "2016 Deere 310SL Backhoe",
    description: "Fleet-maintained backhoe with strong engine hours.",
    state: "CO",
    price: 86000,
    hours: 3600,
    operable: true,
    category: "Backhoe",
    imageQueries: [
      "deere backhoe",
      "backhoe construction",
      "backhoe front loader",
      "backhoe equipment",
    ],
    imageSeed: 511,
    source: "auctionplanet",
    createdAt: "2025-11-27T13:05:00.000Z",
  }),
  makeListing({
    id: "demo-19",
    title: "2019 Case 580N Backhoe",
    description: "Smooth-running backhoe with auxiliary hydraulics.",
    state: "IA",
    price: 104000,
    hours: 1900,
    operable: true,
    category: "Backhoe",
    imageQueries: [
      "case backhoe",
      "backhoe in action",
      "backhoe loader digging",
      "backhoe machine",
    ],
    imageSeed: 521,
    source: "heavyequipment",
    createdAt: "2025-12-06T15:45:00.000Z",
  }),
  makeListing({
    id: "demo-20",
    title: "2015 CAT 416F Backhoe",
    description: "Budget-friendly backhoe with recent service.",
    state: "NV",
    price: 78000,
    hours: 5200,
    operable: true,
    category: "Backhoe",
    imageQueries: [
      "backhoe loader",
      "backhoe worksite",
      "backhoe bucket",
      "backhoe construction equipment",
    ],
    imageSeed: 531,
    source: "auctiontime",
    createdAt: "2025-11-18T09:40:00.000Z",
  }),
  makeListing({
    id: "demo-21",
    title: "2020 JLG 1055 Telehandler",
    description: "High-reach telehandler with low hours.",
    state: "CA",
    price: 132000,
    hours: 1500,
    operable: true,
    category: "Telehandler",
    imageQueries: [
      "telehandler construction",
      "jlg telehandler",
      "telehandler lifting",
      "telehandler boom",
    ],
    imageSeed: 601,
    source: "ritchiebros",
    createdAt: "2025-12-12T16:10:00.000Z",
  }),
  makeListing({
    id: "demo-22",
    title: "2017 Genie GTH-1056 Telehandler",
    description: "Telehandler with stabilized outriggers.",
    state: "TX",
    price: 118000,
    hours: 2800,
    operable: true,
    category: "Telehandler",
    imageQueries: [
      "genie telehandler",
      "telehandler on site",
      "telehandler forks",
      "telescopic handler",
    ],
    imageSeed: 611,
    source: "auctionplanet",
    createdAt: "2025-12-01T07:55:00.000Z",
  }),
  makeListing({
    id: "demo-23",
    title: "2016 CAT TL1055 Telehandler",
    description: "Reliable telehandler with steady boom control.",
    state: "OR",
    price: 98000,
    hours: 4100,
    operable: true,
    category: "Telehandler",
    imageQueries: [
      "cat telehandler",
      "telehandler equipment",
      "telehandler lifting pallet",
      "telehandler worksite",
    ],
    imageSeed: 621,
    source: "ironplanet",
    createdAt: "2025-11-23T10:30:00.000Z",
  }),
  makeListing({
    id: "demo-24",
    title: "2022 SkyTrak 8042 Telehandler",
    description: "Late-model telehandler with service contract.",
    state: "AZ",
    price: 148000,
    hours: 900,
    operable: true,
    category: "Telehandler",
    imageQueries: [
      "skytrak telehandler",
      "telehandler boom lift",
      "telehandler construction equipment",
      "telehandler warehouse",
    ],
    imageSeed: 631,
    source: "machinerytrader",
    createdAt: "2025-12-15T14:15:00.000Z",
  }),
];
